version: "3.2"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  memorystore:
    image: redis:alpine
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes: 
      - ./pg_data:/var/lib/pgadmin
    depends_on: 
      - postgres